// <auto-generated />
using System;
using GasStations_GasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GasStations_GasAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230630013030_AddingCityandCountryTables")]
    partial class AddingCityandCountryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GasStations_GasAPI.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Mississauga"
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Oakville"
                        });
                });

            modelBuilder.Entity("GasStations_GasAPI.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryofOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries_of_Origin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryofOrigin = "France"
                        },
                        new
                        {
                            Id = 2,
                            CountryofOrigin = "Canada"
                        });
                });

            modelBuilder.Entity("GasStations_GasAPI.Models.Gas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("CountryofOriginId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number_of_Pumps")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Purity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryofOriginId");

                    b.ToTable("GasStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "600 Dundas St",
                            CityId = 2,
                            CountryofOriginId = 1,
                            CreatedDate = new DateTime(2023, 6, 29, 21, 30, 30, 519, DateTimeKind.Local).AddTicks(47),
                            Name = "Shell",
                            Number_of_Pumps = 8,
                            Price = 147.30000000000001,
                            Purity = 87,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "1525 Burnhamthorpe Rd",
                            CityId = 1,
                            CountryofOriginId = 2,
                            CreatedDate = new DateTime(2023, 6, 29, 21, 30, 30, 519, DateTimeKind.Local).AddTicks(100),
                            Name = "Petro Canada",
                            Number_of_Pumps = 12,
                            Price = 146.80000000000001,
                            Purity = 87,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GasStations_GasAPI.Models.Gas", b =>
                {
                    b.HasOne("GasStations_GasAPI.Models.City", "City")
                        .WithMany("GasStations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GasStations_GasAPI.Models.Country", "CountryofOrigin")
                        .WithMany("GasStations")
                        .HasForeignKey("CountryofOriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("CountryofOrigin");
                });

            modelBuilder.Entity("GasStations_GasAPI.Models.City", b =>
                {
                    b.Navigation("GasStations");
                });

            modelBuilder.Entity("GasStations_GasAPI.Models.Country", b =>
                {
                    b.Navigation("GasStations");
                });
#pragma warning restore 612, 618
        }
    }
}
